### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by esterkimx**

### CODE REVIEW

**Review by sumboid — APPROVED** [review]
LGTM :+1:

**Comment by esterkimx** [comment]
NOT :-1:

**Comment by tpashkin** [comment]
How about nonpretentious "mug"?

**Review by tpashkin — CHANGES_REQUESTED** [review]
How about we squash that into one commit?

**Review by esterkimx — COMMENTED** [review]
Very good changes :1st_place_medal:

**Comment by tpashkin** [comment]
I'm still not sure about all these "μG". Isn't it supposed to be spelled as /mjuːdʒiː/?

**Review by tpashkin — APPROVED** [review]

**Review by sumboid — CHANGES_REQUESTED** [review]
What about squashing all commits?

**Comment by tpashkin** [comment]
merge --squash

**Review by sumboid — APPROVED** [review]

**Pull request merged**
